#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --nodes=1                                                          


module load gcc/8.3.0
module load anaconda3
eval "$(conda shell.bash hook)"
conda activate discovery_tyssue

export HDF5_USE_FILE_LOCKING='FALSE'
python script_bcsource.py out_1 out_0
